### PR TITLE
Add Checks for Traversable Laws

### PR DESCRIPTION
**Pull request by DavidHarrison**
checkTraversable tests the identity and composition laws for Traversable. Unfortunately, I could not find a good way to use QuickCheck to test naturality, as the test seems to require a polymorphic natural transformation, which I don't know how to make Arbitrary in QuickCheck:

``` purescript
naturality :: forall t f g a b. (Traversable t, Applicative f, Applicative g, Eq (g (t b))) => (forall k. f k -> g k) -> (a -> f b) -> t a -> Boolean
naturality t f x = lhs == rhs
    where lhs :: g (t b)
          lhs = (t <<< traverse f) x
          rhs :: g (t b)
          rhs = traverse (t <<< f) x
```

I have seen that some QuickCheck libraries ask the tester to supply a function in cases like these, but this feels not in keeping with the interface to the library, so I have commented out the test for now.

---
This change is [Reviewable](https://reviewable.io/reviews/garyb/purescript-quickcheck-laws/8)

### CODE REVIEW

**Comment by garyb** [comment]
Thanks, I'll try to get on top of this repo soon, I've been intending to merge a mishmash of things from @paf31's and @freebroccolo's branches - I think `Arbitrary1`/`Coarbitrary1` from @paf31's branch might be able to help us out here to be able to specify `naturality`.

**Comment by paf31** [comment]
Are any of these given for free by parametricity? `naturality` looks like it might be.

**Comment by DavidHarrison** [comment]
According to the [Hackage documentation](https://hackage.haskell.org/package/base-4.7.0.2/docs/Data-Traversable.html), `naturality` is given for free by parametricity, though I think it is the only one.

The following (contrived) Traversable instance satisfies neither identity nor composition:

``` purescript
data Counter a = Counter Int

instance eqCounter :: Eq (Counter a) where
    eq (Counter n) (Counter m) = n == m

instance functorCounter :: Functor Counter where
    map _ (Counter n) = (Counter n)

instance foldableCounter :: Foldable Counter where
    foldr _ z _ = z
    foldl _ z _ = z
    foldMap _ _ = mempty

instance traversableCounter :: Traversable Counter where
    traverse _ (Counter n) = pure $ Counter $ n + 1
    sequence = traverse id
```

**Comment by paf31** [comment]
:+1: Sounds good.

**Pull request closed without merging**
