### PR TITLE
Add checks for BoundedEnum

### PR DESCRIPTION
**Pull request by jacereda**
Sorry for the unimaginative law names, I hope someone else can come up with nicer ones.

### CODE REVIEW

**Comment by jacereda** [comment]
I guess this will fail until `purescript-enums` is tagged.

**Comment by garyb** [comment]
Also need to add the dependency I think!

**Comment by jacereda** [comment]
Doh! I had a `bower link`... >= 2.0.1?

**Comment by garyb** [comment]
Thanks!

**Comment by jacereda** [comment]
Just curious, why do you use `sudo: required` in the travis setup? Don't you prefer the container-based environment?

**Comment by garyb** [comment]
Should I make a release now, or are there any other checks you're working on at the moment?

> Just curious, why do you use sudo: required in the travis setup? Don't you prefer the container-based environment?

The `trusty` image requires it, and that's pretty much essential for PureScript projects, for some reason they build _awfully_ without it - take 10-100x longer and sometimes stall forever.

**Comment by garyb** [comment]
I think `trusty` is container based too.

**Comment by jacereda** [comment]
Looks like they have a beta: https://docs.travis-ci.com/user/trusty-ci-environment/

**Comment by jacereda** [comment]
I think I can write `Enum` tomorrow, let's wait a bit.

**Comment by garyb** [comment]
Okidoke, thanks! We can try the trusty beta thing in that PR too perhaps :)

**Comment by jacereda** [comment]
I'll open a separate request for the trusty beta, but build times are roughly the same and boot time is almost instantaneous. Things aren't as nice when trying to build the purescript compiler itself, I get failures due to lack of disk space and also the build seems slower.

**Pull request merged**
