### PR TITLE
Update to PureScript v0.15.0

### PR DESCRIPTION
**Pull request by JordanMartinez**
**Description of the change**

Backlinking to purescript/purescript#4244

Updates project to compile on v0.15.0 PureScript.

---

**Checklist:**

- [x] Added the change to the changelog's "Unreleased" section with a reference to this PR (e.g. "- Made a change (#0000)")
- [x] Linked any existing issues or proposals that this pull request should close
- [ ] Updated or added relevant documentation
- [ ] Added a test for the contribution (if applicable)

### CODE REVIEW

**Comment by JordanMartinez** [comment]
:ping_pong: @thomashoneyman

**Review by thomashoneyman — APPROVED** [review]
Interesting — I must have missed this in the `purs tidy` updates. Any chance you could add `purs-tidy` with the standard `.tidyrc.json`, run it to format everything, and add the `purs tidy check src test` line to CI?

**Comment by JordanMartinez** [comment]
Can that be done as a separate PR? It'll mess up this diff otherwise.

**Comment by thomashoneyman** [comment]
Yes, absolutely.

**Pull request merged**
